backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "post"
    folder: "_cms/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{author}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Message", name: "message", widget: "text"}
      - {label: "Images", name: "image", widget: "image", media_library: { config: { multiple: true } } }
  - name: "hero"
    label: "Hero"
    folder: "_cms/hero"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{content}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
       - {label: "Content", name: "content", widget: "markdown"}
